baseURL = "https://npow.github.io/"
languageCode = "en-us"
title = "npow"
theme = "PaperMod"
paginate = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  description = "npow's blog"
  author = "npow"
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true
  comments = false

  [params.homeInfoParams]
    Title = "Hey there"
    Content = "Welcome to my blog"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/npow"

  [params.editPost]
    URL = "https://github.com/npow/npow.github.io/tree/main/content"
    Text = "Suggest Changes"
    appendFilePath = true

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    noClasses = false
    guessSyntax = true

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30
